### ISSUE TITLE
evaluate_javascript() throws an error message in calabash-android

### ISSUE THREAD

**Issue by Aravin** [calabash/calabash-android#701] opened 2016-03-24 05:44 UTC
It seems like `evaluate_javascript()` is deprecated since 0.7.0 as per release note. But I am able to use it in my program.

It also performs the action & after execution, the scenario gets failed.

**Error message**
 undefined method `map' for nil:NilClass (NoMethodError)

---
Is there any alternative for `evaluate_javascript()`?

**Comment by TobiasRoikjer** [comment] 2016-03-24 13:16
`evaluate_javascript` is neither deprecated nor removed. What exactly are you running, and what does the stacktrace in adb logcat say?

**Comment by Aravin** [comment] 2016-03-24 13:23
Hi @TobiasRoikjer,

I have seen list of deprecated methods from your documents: https://github.com/calabash/calabash-android/blob/master/ruby-gem/lib/calabash-android/deprecated_actions.map#L9

## Function

`evaluate_javascript('webview', "$('content').scrollTop(100)")`

### More Info

This method worked fine until I update to 0.7.2.
Previously I used 0.5.4

**Comment by TobiasRoikjer** [comment] 2016-03-24 13:26
@Aravin That is referring to an old action (perform_action('evaluate_javascript')). I understand the confusion.

Could you please post the stacktrace from `adb logcat`. If possible, could you also email me the application at tobias@xamarin.com with steps to reproduce. I'll look into it.

**Comment by Aravin** [comment] 2016-03-24 13:32
@TobiasRoikjer ,

I can't share app & full adb log.

**Here is the few log,**

`[ERROR:xwalk_autofill_client.cc(170)] Not implemented reached in virtual void xwalk::XWalkAutofillClient::OnFirstUserGestureObserved()`

**Comment by TobiasRoikjer** [comment] 2016-03-24 13:34
I'm looking for a stacktrace, somthing like
NullPointerException in file xxx:23
           ...
           ...
          ...

Is this even a server issue? What is the full stack trace from the ruby client

**Comment by Aravin** [comment] 2016-03-24 13:39
This `evaluate_javascript()` is first method in my script.

**Log**
```
2016-03-24 19:07:30 - First scenario in feature - reinstalling apps
2016-03-24 19:07:30 - connected_devices: ["4d0095fd4fa13161"]
2016-03-24 19:07:30 - "C:\Users\0232\AppData\Local\Android\sdk/platform-tools/ad
b.exe" -s 4d0095fd4fa13161 forward tcp:34783 tcp:7102
2016-03-24 19:07:30 -
2016-03-24 19:07:30 - Trying to find launchable activity
2016-03-24 19:07:30 - Found launchable activity 'com.ec.demo.Splash'
2016-03-24 19:07:30 - Starting test server using:
2016-03-24 19:07:30 - "C:\Users\0232\AppData\Local\Android\sdk/platform-tools/ad
b.exe" -s 4d0095fd4fa13161 shell am instrument -e target_package com.ikea.catalo
gue.android -e main_activity com.ec.demo.Splash -e test_server_port 7102 -e clas
s sh.calaba.instrumentationbackend.InstrumentationBackend com.ikea.catalogue.and
roid.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2016-03-24 19:07:31 - Checking if instrumentation backend is ready
2016-03-24 19:07:31 - Is app running? true
2016-03-24 19:07:31 - Instrumentation backend not yet ready
2016-03-24 19:07:31 - Checking if instrumentation backend is ready
2016-03-24 19:07:31 - Is app running? true
2016-03-24 19:07:31 - Instrumentation backend not yet ready
2016-03-24 19:07:31 - Checking if instrumentation backend is ready
2016-03-24 19:07:31 - Is app running? true
2016-03-24 19:07:31 - Instrumentation backend not yet ready
2016-03-24 19:07:32 - Checking if instrumentation backend is ready
2016-03-24 19:07:32 - Is app running? true
2016-03-24 19:07:32 - Instrumentation backend is ready!
2016-03-24 19:07:32 - Checking client-server version match...
2016-03-24 19:07:32 - Action: version - Params:
2016-03-24 19:07:32 - Result:'{"bonusInformation":[],"message":"0.7.2","success"
:true}'
2016-03-24 19:07:32 - Client and server versions match (client: 0.7.2, server: 0
.7.2). Proceeding...

2016-03-24 19:08:14 - It looks like your app is no longer running.
It could be because of a crash or because your test script shut it down.
```

**Comment by TobiasRoikjer** [comment] 2016-03-24 14:02
@Aravin That is not what I am looking for. What is the full output from the ruby client?

**Comment by TobiasRoikjer** [comment] 2016-03-24 14:02
After you have run the ruby method evaluate_javascript

**Comment by Aravin** [comment] 2016-03-24 14:11
@TobiasRoikjer 

The above-mentioned log was the full output of ruby client.

I use to run like that `calabash-android run file.apk featurename.feature -v`

Actual error on that line is **undefined method `map' for nil:NilClass (NoMethodError)**

**Comment by TobiasRoikjer** [comment] 2016-03-24 14:22
There should be more text below that. Try opening a console and execute the command.

**Comment by jmoody** [comment] 2016-04-13 10:18
@svandeven This is the issue I was talking about.

**Comment by svandeven** [comment] 2016-04-13 17:09
I get the same issue

example running the command from the console
```
irb(main):001:0> evaluate_javascript("webView","document.getElementsByTagName(\'input\')[3].scrollIntoView(true)")
NoMethodError: undefined method `map' for nil:NilClass
	from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.2/lib/calabash-android/operations.rb:1234:in `evaluate_javascript'
	from (irb):1
	from /opt/boxen/rbenv/versions/2.2.2/bin/irb:11:in `<main>'
irb(main):002:0>
```

I went from calabash-android 0.5.14 to 0.7.2 and then the problem was introduced,

**Comment by TobiasRoikjer** [comment] 2016-04-14 15:50
@Aravin @svandeven Please try upgrading to 0.7.3.pre3

**Comment by TobiasRoikjer** [comment] 2016-04-16 18:28
Released in 0.7.3. https://groups.google.com/forum/#!topic/calabash-android/n30CmBAlqLI

**Closed by TobiasRoikjer** 2016-04-16 18:28 UTC

**Comment by Aravin** [comment] 2016-04-17 02:57
@TobiasRoikjer  I will check. Can you share the reason for this issue?

**Comment by Aravin** [comment] 2016-04-18 08:25
Issue Fixed :+1:
