### ISSUE TITLE
Action 'set_selection' unsuccessful in the webview on 7.1 devices

### ISSUE THREAD

**Issue by zijunt** [calabash/calabash-android#776] opened 2016-10-21 00:36 UTC
Hi
My test failed on 7.1 nexus 6p when try twitter login on a webview page. 

error is:

Then I log in to Twitter webView with the email "XXX" and the password "XXX" # /Users/roytang/Hootsuite/Android-Calabash-Test/features/step_definitions/steps.rb:112
      Action 'set_selection' unsuccessful: java.util.concurrent.TimeoutException (RuntimeError)
      /Users/roytang/Hootsuite/Android-Calabash-Test/features/step_definitions/steps.rb:133:in `/^I log in to Twitter webView with the email "([^\"]*)" and the password "([^\"]*)"$/'
      ../features/Core_NG.feature:11:in`Then I log in to Twitter webView with the email "XXX" and the password "XXX"'

But it works on the 7.0 nexus 6p.

**Comment by TobiasRoikjer** [comment] 2016-10-23 18:00
What version are you using?

**Comment by zijunt** [comment] 2016-10-24 16:58
I was using calabash android 0.8.1, same issue on 0.8.2.
my cucumber version is 1.3.20

**Comment by TobiasRoikjer** [comment] 2016-10-24 20:25
You should post the resulting stacktrace from adb logcat

**Comment by DineshKumar7** [comment] 2016-10-26 03:41
Hai, 
  I am facing the same issue. However It happens on device Nexus 5X (OS 6.0). Please check on the below error. Thanks

`Action 'set_selection' unsuccessful: java.util.concurrent.TimeoutException (RuntimeError)
10-26 11:36:36.986 22917 23733 W System.err: java.lang.RuntimeException: java.util.concurrent.TimeoutException
10-26 11:36:36.988 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.actions.text.TextAction.execute(TextAction.java:63)
10-26 11:36:36.989 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.Command.execute(Command.java:47)
10-26 11:36:36.989 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.runCommand(HttpServer.java:781)
10-26 11:36:36.989 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:761)
10-26 11:36:36.989 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
10-26 11:36:36.989 22917 23733 W System.err: 	at java.lang.Thread.run(Thread.java:818)
10-26 11:36:36.989 22917 23733 W System.err: Caused by: java.util.concurrent.TimeoutException
10-26 11:36:36.989 22917 23733 W System.err: 	at java.util.concurrent.FutureTask.get(FutureTask.java:177)
10-26 11:36:36.989 22917 23733 W System.err: 	at sh.calaba.instrumentationbackend.actions.text.TextAction.execute(TextAction.java:57)`


Calabash-android version - 0.8.1
Server - Ubuntu 14.04

**Comment by maira-maksimova** [comment] 2016-10-26 09:52
Hi,

I am encountering the same issue on Android 5.0. The stack trace is the same as DineshKumar7  posted.

Calabash-android version 0.8.0
cucumber version 2.4.0

**Comment by TobiasRoikjer** [comment] 2016-10-26 18:07
When does this happen?

**Comment by maira-maksimova** [comment] 2016-10-26 18:29
When tries to enter login or password. Focus is on field, keyboard appears but no text is entered.
Most interesting is the fact that on Friday (21/10/2016) tests was working on Galaxy S5. I have not changed tests or updated anything. On other devices tests still work.

**Comment by TobiasRoikjer** [comment] 2016-10-26 18:31
In order to debug the issues, we need to know what exact command that is being executed, and what kind of view is targeted.

**Comment by maira-maksimova** [comment] 2016-10-26 18:43
enter_text("SystemWebView css:'*[name=#{field_name}]'","pass")

**Comment by DineshKumar7** [comment] 2016-10-27 07:50
I use the command - `enter_text("webview css:'input[id=#xxxx]'","xxxxxx")`. 

Note: It started happening recently and not sure what the cause is. May be some nexus system update?. Because it was working before with no such issues and there was no device OS update or calabash version update. 

Details:
Nexus 5x - OS 6.0
Ubuntu 14.04
calabash-android 0.8.1

**Comment by TobiasRoikjer** [comment] 2016-10-27 08:01
@DineshKumar7 Webviews are updated independently of the Android OS through the play store since Lollipop. It could very well be that causing the issue

**Comment by DineshKumar7** [comment] 2016-10-27 08:04
@TobiasRoikjer Is there any workaround for this?. Thanks

**Comment by rKrums** [comment] 2016-10-27 08:04
I'm seeing the same error message when executing `enter_text` on a `android.webkit.WebView` text input field.

Though, I'm seeing this only on samsung devices `SM_G925F, SM_G930F` with android 6.0.1

`calabash-android (0.7.3)`

No gems or devices have been updated recently.

**Comment by maira-maksimova** [comment] 2016-10-27 08:47
I found a workaround. 
I uninstalled updates of Android System WebView application.
Now I have version 43.0.2257.121 and my tests are working again.

**Comment by rKrums** [comment] 2016-10-27 10:06
@maira-maksimova I can confirm, removing update from System WebView did the trick for now. It's not the best, but for now will do. Looks like the latest webView update did this, because the versions are 44.x and 50.x for my devices, and they both work fine.

**Comment by TobiasRoikjer** [comment] 2016-10-29 11:59
Could you please try 0.8.3.pre1, it aims to fix this issue.

**Comment by TobiasRoikjer** [comment] 2016-11-07 15:26
Fixed in `0.8.3.`

**Closed by TobiasRoikjer** 2016-11-07 15:26 UTC

**Comment by kapilag** [comment] 2017-11-24 14:37
I am still seeing this issue, Are you sure this is fixed?
tried on 0.8.4 and 0.9.0 of calabash version both throwing below errors.
Any help is much appreciated.

**Android Version & Device** : Android 7, Samsung S8

**Adb logcat**
`se, capacity:280000, batterySWSelfDischarging:false, misc_event:0, current_event:0, current_now:0
11-24 20:02:28.293  3811  3811 D BatteryService: Sending ACTION_BATTERY_CHANGED.
11-24 20:02:28.294  3811  3811 D SamsungPhoneWindowManager: ACTION_BATTERY_CHANGED - Level :: 100, battStatus :: 5
11-24 20:02:28.295  3811  3811 V UiModeManager: updateLocked: null action, mDockState=0, category=null
11-24 20:02:28.295  3811  3811 D UiModeManager: updateConfigurationLocked: mDockState=0; mCarMode=false; mNightMode=1; uiMode=17
11-24 20:02:28.295  3811  3811 D GameManagerService: new battery level: 100
11-24 20:02:28.299  4184  4184 D KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
11-24 20:02:28.304  4184  4184 D PowerUI : priorPlugType = 2 mPlugType =  2
11-24 20:02:28.308  4184  4184 D BatteryMeterDrawable: isSomethingChanged - false
11-24 20:02:28.309  4184  4184 D BatteryMeterDrawable: isSomethingChanged - false
11-24 20:02:28.309  4184  4184 D BatteryController: onReceive - ACTION_BATTERY_CHANGED : mLevel = 100
11-24 20:02:28.311  4184  4184 D KeyguardUpdateMonitor: handleBatteryUpdate
11-24 20:02:28.345 31363   517 I System.out: URI: //
11-24 20:02:28.345 31363   517 I System.out: params: {json={"command":"set_selection","arguments":[-1,-1]}
11-24 20:02:28.345 31363   517 I System.out: }
11-24 20:02:28.345 31363   517 I System.out: header: {content-type=application/json;charset=utf-8, date=Fri, 24 Nov 2017 14:32:28 GMT, accept=*/*, host=127.0.0.1:34782, content-length=47, user-agent=HTTPClient/1.0 (2.8.3, ruby 2.3.1 (2016-04-26))}
11-24 20:02:28.345 31363   517 I System.out: params: {json={"command":"set_selection","arguments":[-1,-1]}
11-24 20:02:28.345 31363   517 I System.out: }
11-24 20:02:28.345 31363   517 I System.out: ProP json = {"command":"set_selection","arguments":[-1,-1]}
11-24 20:02:28.345 31363   517 I System.out: files: {}
11-24 20:02:28.345 31363   517 I System.out: command: {"command":"set_selection","arguments":[-1,-1]}
11-24 20:02:28.348 31363   517 I InstrumentationBackend: Got command:'Command:'Line:null,set_selection', arguments:'[-1, -1]'
11-24 20:02:28.349 31363   517 W System.err: java.lang.NullPointerException: null receiver
11-24 20:02:28.349 31363   517 W System.err: 	at java.lang.reflect.Field.get(Native Method)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.actions.text.InfoMethodUtil.getInputConnection(InfoMethodUtil.java:50)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.actions.text.TextAction.execute(TextAction.java:36)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.Command.execute(Command.java:47)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.runCommand(HttpServer.java:781)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:761)
11-24 20:02:28.349 31363   517 W System.err: 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
11-24 20:02:28.349 31363   517 W System.err: 	at java.lang.Thread.run(Thread.java:762)
11-24 20:02:28.359 31363   517 I System.out: result:{"bonusInformation":["Exception stack trace:\njava.lang.NullPointerException: null receiver\n\tat java.lang.reflect.Field.get(Native Method)\n\tat sh.calaba.instrumentationbackend.actions.text.InfoMethodUtil.getInputConnection(InfoMethodUtil.java:50)\n\tat sh.calaba.instrumentationbackend.actions.text.TextAction.execute(TextAction.java:36)\n\tat sh.calaba.instrumentationbackend.Command.execute(Command.java:47)\n\tat sh.calaba.instrumentationbackend.actions.HttpServer.runCommand(HttpServer.java:781)\n\tat sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:761)\n\tat sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)\n\tat java.lang.Thread.run(Thread.java:762)\n"],"message":"null receiver","success":false}`

**Calabash exception**
`RuntimeError: Action 'set_selection' unsuccessful: null receiver
	from /Users/kapila/.rvm/gems/ruby-2.3.1@loganberry/gems/calabash-android-0.8.4/lib/calabash-android/operations.rb:425:in `block in perform_action'
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /Users/kapila/.rvm/gems/ruby-2.3.1@loganberry/gems/calabash-android-0.8.4/lib/calabash-android/operations.rb:414:in `perform_action'
	from /Users/kapila/.rvm/gems/ruby-2.3.1@loganberry/gems/calabash-android-0.8.4/lib/calabash-android/operations.rb:92:in `perform_action'
	from /Users/kapila/.rvm/gems/ruby-2.3.1@loganberry/gems/calabash-android-0.8.4/lib/calabash-android/text_helpers.rb:55:in `set_selection'
	from /Users/kapila/.rvm/gems/ruby-2.3.1@loganberry/gems/calabash-android-0.8.4/lib/calabash-android/text_helpers.rb:27:in `enter_text'
	from (irb):1
	from /Users/kapila/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
irb(main):002:0>`
