### ISSUE TITLE
Publish 0.8.0.pre2

### ISSUE THREAD

**Issue by nicolai86** [calabash/calabash-android#747] opened 2016-07-08 07:12 UTC
Hey @TobiasRoikjer,

can you push the new prelease version to rubygems? Otherwise you need to hack around the missing `TestServer.apk`  when using `gem "calabash-android", github: "calabash/calabash-android"` …

🙏

**Comment by TobiasRoikjer** [comment] 2016-07-08 12:53
We appreciate the activity of the community very much, it is important to the Calabash project. This includes people reporing issues, contributors, helpers and our users.

Triaging work and scheduling tasks, however, is complex and requires a lot of overhead. Releasing Calabash is one of them. We try to release as often as possible while going to great lengths to ensure that Calabash is stable and does not contain regressions. Pre-releases are released without as much scrutiny, and should be regarded as non-stable.

We use the Github issues as a way for the community to report and discuss issues with Calabash itself, not for scheduling tasks or a broader discussion in general. In short, this topic is not an issue with Calabash. For a broader community channel, I suggest joining our (Gitter)[https://gitter.im/calabash/calabash0x] which is a live chat. In general, please do not ping any maintainer (or contributor) unless it is a direct reply to a topic (issue or PR), as the Calabash project involves a lot of people and is not a single-person effort.

The pre-release has since this post been published on Rubygems, which was planned.

In the future, I suggest building from source yourself, by running `bundle exec rake build` in the "ruby-gems" directory.

Thank you :)

**Closed by TobiasRoikjer** 2016-07-08 12:53 UTC
